apiVersion: v1
kind: Service
metadata:
  name: debugging-demo
  labels:
    app: debugging-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: debugging-demo
